"""empty message

Revision ID: 2ecd7e54e6e2
Revises: f13cdec78f35
Create Date: 2024-12-02 17:29:46.575338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ecd7e54e6e2'
down_revision = 'f13cdec78f35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_admin_key_id'), ['admin_key_id'], unique=False)

    with op.batch_alter_table('key', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_key_admin_key_id'), ['admin_key_id'], unique=False)
        batch_op.create_unique_constraint(None, ['key'])

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_collection_id'), ['collection_id'], unique=False)

    with op.batch_alter_table('person_face_embedding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_face_embedding_image_id'), ['image_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_face_embedding_person_id'), ['person_id'], unique=False)

    with op.batch_alter_table('person_face_image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_face_image_person_id'), ['person_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('user_face_embedding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_face_embedding_image_id'), ['image_id'], unique=False)

    with op.batch_alter_table('user_face_image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_face_image_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_face_image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_face_image_user_id'))

    with op.batch_alter_table('user_face_embedding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_face_embedding_image_id'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('person_face_image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_face_image_person_id'))

    with op.batch_alter_table('person_face_embedding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_face_embedding_person_id'))
        batch_op.drop_index(batch_op.f('ix_person_face_embedding_image_id'))

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_collection_id'))

    with op.batch_alter_table('key', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_key_admin_key_id'))

    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_admin_key_id'))

    # ### end Alembic commands ###
