"""empty message

Revision ID: 3a931d3b87bf
Revises: 2f3e54a38518
Create Date: 2024-11-17 01:11:44.046314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a931d3b87bf'
down_revision = '2f3e54a38518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_collection',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], name='access-collection-fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['key_id'], ['key.id'], name='access-key-fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'key_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_collection')
    # ### end Alembic commands ###
