"""empty message

Revision ID: 85125b398665
Revises: 0f946f5f6cec
Create Date: 2024-11-05 05:07:54.056669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85125b398665'
down_revision = '0f946f5f6cec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_face_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', sa.LargeBinary(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_face_image', schema=None) as batch_op:
        batch_op.drop_column('embedding')

    # ### end Alembic commands ###
