"""empty message

Revision ID: be7ec1cffd64
Revises: 85125b398665
Create Date: 2024-11-06 22:52:29.705912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be7ec1cffd64'
down_revision = '85125b398665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_face_image', schema=None) as batch_op:
        batch_op.drop_column('src_img_url')
        batch_op.drop_column('embedding')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_face_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', sa.BLOB(), nullable=False))
        batch_op.add_column(sa.Column('src_img_url', sa.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
